#!/usr/bin/env bun
// Generate the Why3 counterpart and compare fresh Bend CLI processes only.
import * as assert from "node:assert/strict";
import * as child from "node:child_process";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const HERE = import.meta.dirname;
const ROOT = path.resolve(HERE, "../../..");
const HEADER = "# Generated by compare.ts --write-source from main.bend.\n"
  + "# All statements and computational definitions are unchanged.\n"
  + "# Check with --induct a --induct xs --induct t; see WHY3.md.\n\n";
const PROOF = /^(?:add_(?:zero|succ|comm)|aadd\d+_(?:zero|succ|comm)|bcat\d+_(?:nil|assoc)|blen\d+_cat|(?:cmir|csize)\d+_mir)$/;
const original = fs.readFileSync(path.join(HERE, "main.bend"), "utf8");
const blocks = original.split(/(?=^(?:type|law|def) )/m);
const removed: string[] = [];
const source = HEADER + blocks.filter((block) => {
  const name = /^def ([^\s(:]+)/.exec(block)?.[1];
  if (!name || !PROOF.test(name)) return true;
  removed.push(name);
  return false;
}).join("");
assert.equal(removed.length, 8537, "The benchmark changed; review the proof selection");
const args = process.argv.slice(2);
if (args.length === 1 && args[0] === "--write-source") {
  fs.writeFileSync(path.join(HERE, "why3.bend"), source);
  console.log("Generated why3.bend: " + removed.length + " automatic laws");
  process.exit(0);
}
assert.equal(fs.readFileSync(path.join(HERE, "why3.bend"), "utf8"), source,
  "why3.bend must preserve every original block except the selected proof definitions");
let repeats = 1;
let jobs = Math.min(16, os.availableParallelism());
let output = path.join(ROOT, ".tmp", "checker-proofs-" + new Date().toISOString().replace(/[:.]/g, "-"));
let provers = ["z3", "alt-ergo"];
for (let i = 0; i < args.length; i += 2) {
  const value = args[i + 1];
  assert.ok(value && !value.startsWith("--"), args[i] + " needs a value");
  if (args[i] === "--repeats") {
    assert.match(value, /^[1-9]\d*$/);
    repeats = Number(value);
  } else if (args[i] === "--jobs") {
    assert.match(value, /^[1-9]\d*$/);
    jobs = Number(value);
    assert.ok(jobs <= 64, "--jobs must be from 1 to 64");
  } else if (args[i] === "--out") output = path.resolve(value);
  else if (args[i] === "--provers") provers = value.split(",").filter(Boolean);
  else throw new Error("Unknown argument: " + args[i]);
}
assert.ok(provers.length > 0, "Select at least one prover");
const why3 = process.env.BEND_WHY3 ?? "why3";
const config = process.env.WHY3CONFIG;
assert.ok(config && fs.existsSync(config), "Set WHY3CONFIG to the detected prover configuration");
fs.mkdirSync(output, { recursive: true });
const sha = (data: string | Buffer) => crypto.createHash("sha256").update(data).digest("hex");
const lines = (text: string) => text.split(/\r?\n/).filter((l) => l.trim() && !l.trimStart().startsWith("#")).length;
type Sample = { repeat: number; variant: string; seconds: number; ok: boolean; exitCode: number;
  atpGoals: number; cacheFiles: string[]; command: string[] };
const report = {
  timestamp: new Date().toISOString(), host: { cpu: os.cpus()[0]?.model, platform: os.platform(), arch: os.arch(), cpus: os.availableParallelism() },
  bun: child.execFileSync(process.execPath, ["--version"], { encoding: "utf8" }).trim(),
  why3: child.execFileSync(why3, ["--version"], { encoding: "utf8" }).trim(),
  proverConfiguration: fs.readFileSync(config, "utf8"),
  revision: child.execFileSync("git", ["rev-parse", "HEAD"], { cwd: ROOT, encoding: "utf8" }).trim(),
  sha256: Object.fromEntries(["bend2/main.ts", "bend2/bend.ts", "bend2/why3.ts", "bench/checker/proofs_3200/main.bend", "bench/checker/proofs_3200/why3.bend"]
    .map((f) => [f, sha(fs.readFileSync(path.join(ROOT, f)))])),
  repeats, provers, jobs, timeout: 1, induct: ["a", "xs", "t"], automaticLaws: removed.length,
  lines: { original: lines(original), why3: lines(source) },
  cachePolicy: "Fresh CLI process, TMPDIR and XDG directories for every sample; Bun disk transpiler cache disabled; no proof/session reuse. Normal within-run memoization and OS file caching remain enabled. Telemetry disabled.",
  samples: [] as Sample[],
};
const save = () => fs.writeFileSync(path.join(output, "results.json"), JSON.stringify(report, null, 2) + "\n");
const files = (dir: string): string[] => fs.readdirSync(dir, { withFileTypes: true }).flatMap((f) =>
  f.isDirectory() ? files(path.join(dir, f.name)) : [path.join(dir, f.name)]);
save();
console.log("Results: " + output);
for (let repeat = 1; repeat <= repeats; repeat++) {
  const variants = repeat % 2 ? ["original", "why3"] : ["why3", "original"];
  for (const variant of variants) {
    const work = fs.mkdtempSync(path.join(os.tmpdir(), "bend-checker-"));
    try {
      for (const dir of ["tmp", "cache", "config"]) fs.mkdirSync(path.join(work, dir));
      const conf = path.join(work, "config", "why3.conf");
      fs.copyFileSync(config, conf);
      const env = Object.fromEntries(Object.entries(process.env).filter(([k]) => !k.startsWith("BEND_WHY3")));
      Object.assign(env, { BEND_NO_TELEMETRY: "1", BUN_RUNTIME_TRANSPILER_CACHE_PATH: "0", WHY3CONFIG: conf,
        TMPDIR: path.join(work, "tmp"), XDG_CACHE_HOME: path.join(work, "cache"), XDG_CONFIG_HOME: path.join(work, "config") });
      const command = [process.execPath, path.join(ROOT, "bend2/main.ts"), path.join(HERE, variant === "original" ? "main.bend" : "why3.bend")];
      if (variant === "why3") command.push("--why3-bin", why3, "--timeout", "1", "--jobs", String(jobs),
        ...provers.flatMap((p) => ["--prover", p]), ...report.induct.flatMap((v) => ["--induct", v]));
      console.log("Starting " + variant + " sample " + repeat);
      const log = fs.openSync(path.join(output, variant + "." + repeat + ".log"), "w");
      const start = performance.now();
      let status: number;
      try {
        status = await new Promise<number>((resolve, reject) => {
          const proc = child.spawn(command[0], command.slice(1), { cwd: ROOT, env, stdio: ["ignore", log, log] });
          const timer = setInterval(() => console.log(variant + " sample " + repeat + ": " + ((performance.now() - start) / 1000).toFixed(0) + "s elapsed"), 30000);
          proc.once("error", (e) => { clearInterval(timer); reject(e); });
          proc.once("exit", (code) => { clearInterval(timer); resolve(code ?? -1); });
        });
      } finally { fs.closeSync(log); }
      const seconds = (performance.now() - start) / 1000;
      const text = fs.readFileSync(path.join(output, variant + "." + repeat + ".log"), "utf8");
      const atpGoals = [...text.matchAll(/Why3 proved (\d+) obligation/g)].reduce((n, m) => n + Number(m[1]), 0);
      const ok: boolean = status === 0 && text.includes("All terms check.") && atpGoals === (variant === "why3" ? removed.length : 0);
      report.samples.push({ repeat, variant, seconds, ok, exitCode: status, atpGoals,
        cacheFiles: files(path.join(work, "cache")).map((f) => path.relative(work, f)), command });
      save();
      console.log((ok ? "PASS " : "FAIL ") + variant + ": " + seconds.toFixed(3) + "s; " + atpGoals + " ATP goals");
      assert.ok(ok, "See " + path.join(output, variant + "." + repeat + ".log"));
    } finally { fs.rmSync(work, { recursive: true, force: true }); }
  }
}
const median = (xs: number[]) => {
  xs.sort((a, b) => a - b);
  return (xs[Math.floor((xs.length - 1) / 2)] + xs[Math.floor(xs.length / 2)]) / 2;
};
const table = ["| Version | Source lines | ATP goals | Check time (s) |", "| --- | ---: | ---: | ---: |",
  ...(["original", "why3"] as const).map((variant) => "| " + variant + " | " + report.lines[variant] + " | "
    + (variant === "why3" ? removed.length : 0) + " | " + median(report.samples.filter((s) => s.variant === variant).map((s) => s.seconds)).toFixed(3) + " |"),
  "", "Nonblank, noncomment source lines. " + (repeats === 1 ? "One fresh full CLI check per version."
    : "Median of " + repeats + " fresh full CLI checks per version."), report.cachePolicy];
fs.writeFileSync(path.join(output, "comparison.md"), table.join("\n") + "\n");
console.log(table.join("\n"));
